In [1]:
from evaluator import *
from leaf_classification import ImageRecognition
from sklearn import metrics
import tensorflow as tf
import matplotlib.pyplot as plt
import random
import math
import scipy
from scipy import ndimage
%matplotlib inline

In [2]:
ir = ImageRecognition()
# ir.load_processed_data('data/data_image_100.pkl')
ir.load_processed_data('data/data_csv_only.pkl')
run_name = 'mlp_02-23-2017_03:40:54-199'

test = ir.data[:,:-99]
label = ir.data[:,-99:]
print test.shape
print label.shape

test=test
test_labels=label
id=ir.identifier
one_hot_names=ir.one_hot_namesl
n_input=ir.n_input
model_location="weight/" + run_name
tensor_name="output/activation:0"
input_x_tensor_name="input_1/x-input:0"
input_y_tensor_name="input_1/y-input:0"
save_dir="predictions/"
save_name="model_" + run_name + ".pkl"
learning_rate=0.01

(990, 192)
(990, 99)


In [5]:
entry = 5
sess = load_session(model_location)
norm_tensor = sess.graph.get_tensor_by_name('output/activation:0')
out = sess.run(norm_tensor, feed_dict={'input_1/x-input:0':np.reshape(test, [990,192]), 'input/keep_probability:0':1.})
# norm_tensor2 = sess.graph.get_tensor_by_name('cross_entropy_1:0')
# out2 = sess.run(norm_tensor2, feed_dict={'input_1/x-input:0':np.reshape(test[entry], [1,192]), 'input/keep_probability:0':1.})
print label[entry], np.argmax(label[entry])
print out[entry], np.argmax(out[entry])

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.] 40
[[ 0.23917449 -1.39175415 -1.91804802 ...,  0.34924513 -1.16286266
   2.98868799]
 [ 2.23444605 -0.88539439 -1.50252867 ..., -0.91536444 -1.74127901
   0.85486662]
 [ 7.09397936  0.23490465  1.94600487 ..., -1.99244523  0.31982201
   4.15675259]
 ..., 
 [ 1.51612449  2.77143931 -3.42368937 ..., -1.0715493  -2.23869491
  -0.49481168]
 [ 1.01582789 -0.54409844 -0.37028131 ..., -1.29849279 -3.22921562
  -0.77993643]
 [-2.81161594 -1.13790643 -2.34637713 ...,  2.47407246 -1.59983671
   2.85932279]] 9932


In [7]:
print label[entry], np.max(label[entry])
print out[entry], np.max(out[entry])

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.] 1.0
[ -2.10302186e+00   4.42547321e-01   3.90615439e+00  -3.89382869e-01
  -9.29387093e-01   7.60226905e-01   2.45249653e+00  -4.74646187e+00
   3.01466227e-01  -3.88843822e+00  -1.35958266e+00  -4.91557503e+00
  -3.88154054e+00  -5.68693876e+00  -4.98669815e+00   2.82699442e+00
  -1.63032448e+00  -5.74829578e+00  -3.70819449e+00  -3.37889344e-02
  -6.55730188e-01   3.63809252e+00   1.89562380e+00   1.57892394e+00
   5.51891387e-01   5.84136391e+00  -2.43103004e+00  -3.86812031e-01
   2.56607914e+00   3.16714048e+00   2.03607464e+00   6.66414785e+00
   4.93066639e-01   4.63615084e+00   7.72

In [ ]:
type(np.reshape(test[0],[1,192])[0][0])

In [ ]:
sess.graph.get_operations()

In [8]:
# with open("predictions/cnn_02-22-2017_08:46:07-299", 'rb') as input:
    #  with open("predictions/labels", 'rb') as input:
if True:
#     cnn_pred = pickle.load(input)
    cnn_pred = out
    cnn_pred = sklearn.preprocessing.normalize(cnn_pred, axis=1) #normalize
    top_3_idx = np.argpartition(cnn_pred, -3, axis=1)[:,-3:]
    keeper = np.zeros(cnn_pred.shape)
    for j in range(cnn_pred.shape[0]):
        zeros = np.zeros(cnn_pred.shape[1])
        zeros[top_3_idx[j]] = 1
        keeper[j] = cnn_pred[j] * zeros
    cnn_pred = keeper

In [70]:
pred = np.argmax(cnn_pred, axis=1)
true = np.argmax(label, axis=1)
isEqual = np.equal(pred, true)
right = np.nonzero(isEqual)[0]
wrong = np.nonzero(~isEqual)[0]

In [72]:
for i in range(wrong.shape[0]):
    print pred[wrong[i]]
    print true[wrong[i]]
    print top_3_idx[wrong[i]]
    best_3_values = cnn_pred[wrong[i]][top_3_idx[wrong[i]]]
    print best_3_values
    print np.std(best_3_values)

73
69
[83 69 73]
[ 0.16185778  0.1700812   0.17117131]
0.00415738443595
83
26
[52 26 83]
[ 0.14914937  0.21632928  0.21890166]
0.032292308466
39
40
[34 40 39]
[ 0.14990336  0.22531292  0.22898221]
0.0364440677449
28
15
[29 15 28]
[ 0.16350652  0.20566145  0.21310128]
0.0218378593938
82
63
[63 78 82]
[ 0.2067841   0.22485149  0.23559746]
0.0118889132809
37
38
[23 38 37]
[ 0.16965099  0.21398032  0.25806046]
0.0360930621795
57
88
[88 27 57]
[ 0.21173678  0.23168011  0.27127796]
0.0247450972156
66
28
[67 15 66]
[ 0.16170026  0.17025608  0.17961657]
0.0073167602873
83
52
[81 52 83]
[ 0.19227357  0.27290609  0.27887022]
0.0394914264302
30
42
[90 42 30]
[ 0.20437907  0.20983772  0.21851347]
0.00581995669552
73
81
[86 42 73]
[ 0.19459395  0.19900195  0.24659298]
0.023542481826
64
81
[55 81 64]
[ 0.14530432  0.2333044   0.23975395]
0.0430843375541
56
69
[53 69 56]
[ 0.15941167  0.2116189   0.28273568]
0.0505437119957
83
52
[52 83 46]
[ 0.19701083  0.24039154  0.2266888 ]
0.0181059620997
53
55


In [73]:
for i in range(right.shape[0]):
    print pred[right[i]]
    print true[right[i]]
    print top_3_idx[right[i]]
    best_3_values = cnn_pred[right[i]][top_3_idx[right[i]]]
    print best_3_values
    print np.std(best_3_values)

3
3
[98  3 46]
[ 0.15527026  0.21337156  0.18065107]
0.0237827586144
49
49
[10 11 49]
[ 0.15153439  0.15257949  0.32454509]
0.0813128109531
65
65
[54  0 65]
[ 0.17297146  0.23752473  0.34476519]
0.0708525272726
94
94
[10 83 94]
[ 0.17709398  0.18564747  0.30472302]
0.0582535849786
84
84
[79  8 84]
[ 0.13454936  0.14816685  0.34396014]
0.0956691742199
40
40
[31 34 40]
[ 0.18340662  0.21273063  0.2477417 ]
0.0262988692327
54
54
[65 54 76]
[ 0.12526235  0.30557162  0.19571291]
0.074194674911
78
78
[ 6 82 78]
[ 0.18793581  0.23065485  0.30614033]
0.0488708985541
53
53
[83 50 53]
[ 0.15909657  0.18379711  0.30432886]
0.0634476494807
89
89
[58 17 89]
[ 0.18900809  0.19388014  0.34608454]
0.0729253234063
98
98
[94 53 98]
[ 0.16099805  0.19238555  0.35658926]
0.0857670966499
16
16
[11 93 16]
[ 0.19686046  0.20509097  0.30861178]
0.0508512608273
74
74
[54 20 74]
[ 0.16413547  0.22628734  0.31848714]
0.0634105623476
50
50
[ 3 83 50]
[ 0.17929034  0.22018918  0.30618486]
0.052883719763
58
58
[13 

In [ ]:
plt.imshow(np.reshape(test[0],[100,100]), cmap='gray')

In [ ]:
ir = ImageRecognition()
ir.load_processed_data('data_no_id_100.pkl')
# ir.load_processed_data('data_csv_only.pkl')

In [ ]:
def plotImages(units):
    filters = units.shape[0]
    plt.figure(1, figsize=(10,10))
    n_columns = 6
    n_rows = math.ceil(filters / n_columns) + 1
    for i in range(filters):
        plt.subplot(n_rows, n_columns, i+1)
        plt.title('Filter ' + str(i))
        plt.imshow(units[i,:,:], interpolation="nearest", cmap="gray")

In [ ]:
ir.data[0].shape
pic = ir.data[0:3,:10000]
pic = np.reshape(pic, [3, 100,100,1])

In [ ]:
plotImages(pic)

In [ ]:
# rotated_pic = tf.contrib.image.rotate(pic, random.uniform(0,6.28))
pic2 = tf.placeholder(tf.float32, [None,100,100, 1])
rotated_pic = tf.contrib.image.rotate(pic2, 200)
sess = tf.Session()
output = sess.run(rotated_pic, feed_dict={pic2:pic})
# plt.imshow(output, cmap="gray")
output = np.reshape(output, [3,100,100])
print output.shape
plotImages(output)

In [ ]:
print pic.shape
from random import randint
degree = randint(0,3) * 90 + randint(-15,15)
print degree
out = scipy.ndimage.rotate(pic, degree, axes=(1,2), order=0)
# out = scipy.ndimage.rotate(pic, 105, axes=(1,2), order=0)
plotImages(out)
np.max(out)

In [ ]:
from scipy import misc
misc.imrotate(pic, )

In [ ]:
run_name = '02-20-2017_05:18:32'
#run_name = 'mlp_02-20-2017_06:09:32'
names, train_index, test_index = load_metadata('metadata_' + run_name + '.pkl')

In [ ]:
#tmp = ir.data[test_index[0]]
#test = tmp[:,:-99]
#label = tmp[:, -99:]
test = ir.data[:,:-99]
label = ir.data[:,-99:]
print test.shape
print label.shape
metadata = dict(
    test=test,
    test_labels=label,
    id=ir.identifier,
    one_hot_names=ir.one_hot_names,
    n_input=ir.n_input,
    model_location="model/model_" + run_name + "-999",
    tensor_name="output/activation:0",
    input_x_tensor_name="input_1/x-input:0",
    input_y_tensor_name="input_1/y-input:0",
    save_dir="predictions/",
    save_name="model_" + run_name + ".pkl",
    learning_rate=0.01)

In [ ]:
if True:
    ir = ImageRecognition()
    ir.load_processed_data('data/data_image_100.pkl')
    #  load_metadata('metadata_02-20-2017_02:10:32.pkl')
    test = ir.data[:, :-99]
    label = ir.data[:, -99:]
    metadata = dict(
        test=test,
        test_labels=label,
        id=ir.identifier,
        one_hot_names=ir.one_hot_names,
        n_input=ir.n_input,
        model_name="cnn_02-22-2017_08:46:07-299",
        weight_dir="weight/",
        prediction_dir="predictions/",
        tensor_name="output/activation:0",
        input_x_tensor_name="input_1/x-input:0",
        input_y_tensor_name="input_1/y-input:0",
        learning_rate=0.01,
        debug=True)

In [ ]:
# load_session_and_save_prediction(**metadata)

In [ ]:
pred = load_predictions(metadata['prediction_dir'] + metadata['model_name'])
best_guess_index, actual_index, correct_predictions, correct_percentage = compare_with_true(pred, (metadata['test_labels']))
print sklearn.metrics.classification_report(actual_index, best_guess_index,target_names=metadata['one_hot_names'])

In [ ]:
pred = load_predictions(metadata['save_dir'] + metadata['save_name'])
best_guess_index, actual_index, correct_predictions, correct_percentage = compare_with_true(pred[test_index[0]], (metadata['test_labels'])[test_index[0]])
print sklearn.metrics.classification_report(actual_index, best_guess_index,target_names=metadata['one_hot_names'])
#print sklearn.metrics.classification_report(best_guess_index, actual_index, target_names=metadata['one_hot_names'])

In [ ]:
cm = sklearn.metrics.confusion_matrix(actual_index, best_guess_index)
plot_confusion_matrix(cm, metadata['one_hot_names'])